name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/yarn.lock') }}
          path: |
            node_modules
            */*/node_modules

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: |
          yarn install --ignore-optional
          spago install
          # spago install --config bench-spago.dhall

      - name: Build source
        run: spago build --no-install --purs-args '--censor-lib --strict'

      - name: Run tests
        run: spago test
